language: node_js
node_js:
  - "4.4"
  - "6.2"
before_script:
  # Install ImageMagick
  - sudo apt-get install imagemagick -y
  # Install Unoconv
  - sudo add-apt-repository ppa:libreoffice/ppa -y
  - sudo apt-get update
  - sudo apt-get install libreoffice libreoffice-script-provider-python -y
  - sudo apt-get install unoconv -y
  - sudo apt-get --only-upgrade install cpio libgcrypt11 libnss3 libreoffice-pdfimport multiarch-support -y
